version: '3.4'

networks:
  dev:
   driver: bridge

services:
  helloworld:
    image: ${DOCKER_REGISTRY-}helloworld
    depends_on:
     - "app_db"    
    ports:
     - "8080:8080"
    build:
      context: .
      dockerfile: HelloWorld/Dockerfile
    environment:
     - ConnectionStrings__DefaultConnection=Server=app_db;Database=SampleDriversDB;Port=3306;Uid=mysql;Pwd=mysql;Pooling=True;
     - ASPNETCORE_URLS=http://+:8080
    networks:
     - dev

  app_db:
    image: mysql:latest
    container_name: app_db
    environment:
     - MYSQL_ROOT_PASSWORD=mysuperPassword
     - MYSQL_USER=mysql
     - MYSQL_PASSWORD=mysql
     - MYSQL_DATABASE=SampleDriversDB
    ports:
     - 5433:3306
    restart: always
    volumes:
     - app_data:/var/lib/minesql/data
    networks:
     - dev
volumes:
 app_data:

